version: "2.1"
services:
  web:
    # replace imageName with your image name (block in your case)
    image: blog-app:latest
    ports:
      - 8080:8080 # Replace the port of your application here if used
    depends_on: 
      - db
  db:
    image: mongo:latest
    volumes:
      - ./database:/data
    ports:
      - "27017:27017"